"""Foreign keys added

Revision ID: 5b53a23e1745
Revises: 
Create Date: 2022-05-27 08:56:55.797174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b53a23e1745'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('mail', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('about', sa.Text(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('username')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_name', sa.String(length=50), nullable=False),
    sa.Column('sun_low', sa.Integer(), nullable=False),
    sa.Column('sun_hi', sa.Integer(), nullable=False),
    sa.Column('hum_low', sa.Integer(), nullable=False),
    sa.Column('hum_hi', sa.Integer(), nullable=False),
    sa.Column('salt_low', sa.Integer(), nullable=False),
    sa.Column('salt_hi', sa.Integer(), nullable=False),
    sa.Column('fert_low', sa.Integer(), nullable=False),
    sa.Column('fert_hi', sa.Integer(), nullable=False),
    sa.Column('plant_pic', sa.String(), nullable=True),
    sa.Column('user_id_plant', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_plant'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pot_location', sa.String(), nullable=True),
    sa.Column('sun_value', sa.Integer(), nullable=False),
    sa.Column('hum_value', sa.Integer(), nullable=False),
    sa.Column('salt_value', sa.Integer(), nullable=False),
    sa.Column('fert_value', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('user_id_pot', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['user_id_pot'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pots')
    op.drop_table('plants')
    op.drop_table('users')
    # ### end Alembic commands ###
